### ISSUE TITLE
Missing required packages

### ISSUE THREAD

**Issue by dkoslicki** [dkoslicki/PressPurtCoreAlg#11]
@danagibbon Correct me if I'm wrong, but shouldn't [this line](https://github.com/dkoslicki/PressPurtCoreAlg/blob/gibbond/R/scripts.R#L90) contain everything in [requirements.txt](https://github.com/dkoslicki/PressPurtCoreAlg/blob/gibbond/requirements.txt)? I got a ``no module named sympy`` error otherwise when running ``ComputeEntryWisePerturbationExpectation``, which was solved with:
```bash
source activate r-reticulate
pip install sympy
```

**Comment by danagibbon** [comment]
@dkoslicki you are correct. I can't recall off the top of my head if `sympy` was one of the packages that had to be installed manually. I know that pandas & scipy didn't work from R. I will have to test it.

**Comment by dkoslicki** [comment]
Ok, go ahead and test it from R again, and otherwise give instructions about how to do it via the command line as I mentioned above.

**Comment by danagibbon** [comment]
Ended up working from R. Fixed with: c3dc04b1dc701903649733f69143053122650da4
