### ISSUE TITLE
Error in GenerateEntryWiseFigures

### ISSUE THREAD

**Issue by marknovak** [dkoslicki/PressPurtCoreAlg#12]
Installation appears to have worked great.  
`PreProsMatrix` returned by ` PreprocessMatrix` applied to "IGP.csv" looks good.   
Last bit of `` ComputeEntryWisePerturbationExpectation `` return may evidence problems:
```
$distributions$`(2, 3)`
<scipy.stats._distn_infrastructure.rv_frozen>

$distributions$`(3, 1)`
<scipy.stats._distn_infrastructure.rv_frozen>

$distributions$`(3, 2)`
<scipy.stats._distn_infrastructure.rv_frozen>

$distributions$`(3, 3)`
<scipy.stats._distn_infrastructure.rv_frozen>


$expected_num_switch
     0    1    2    3
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0
```
Running ` GenerateEntryWiseFigures(EntryWise=Entrywise, 
                          all_numswitch_plots = FALSE, 
                         list_of_numswitch_to_plot=list_of_numswitch_to_plot)`

gives:
> Error in `[.python.builtin.object`(asymp_stab, (k + 1), (l + 1), ) :  unused arguments (alist((l + 1), ))

**Comment by danagibbon** [comment]
I believe this line is the issue:
https://github.com/dkoslicki/PressPurtCoreAlg/blob/593cf914cc1983d6d0ea5782b820b4b6dfb31113/R/scripts.R#L398
I had a similar problem when I used reticulate version 1.9 but it appeared to be fixed when I upgraded to 1.11. I now require version 1.11 in the package. Thanks for letting me know!

**Comment by dkoslicki** [comment]
Thanks @danagibbon! @marknovak, let us know if upgrading reticulate works for you

**Comment by marknovak** [comment]
Works!  thanks
