### ISSUE TITLE
`GenerateEntryWiseFigures all_plots=T` Error in do.call(c, ns[[2]])

### ISSUE THREAD

**Issue by marknovak** [dkoslicki/PressPurtCoreAlg#13]
Running  `GenerateEntryWiseFigures(EntryWise=Entrywise, all_numswitch_plots = TRUE)` on "Quantitative/Stone1990.csv" produces:
> Error in do.call(c, ns[[2]]) : second argument must be a list

Producing only a single figure does fine.

**Comment by marknovak** [comment]
The same happens with "Vandermeer1969.csv" as well.  (Issue title edited accordingly.)

**Comment by marknovak** [comment]
The same "error" is thrown for single figure plots for some matrices (e.g., "Qualitative/Hansen2017.csv") even though the single figure is actually plotted.

**Comment by dkoslicki** [comment]
This appears to no longer be an issue (tested on all matrices and could not replicate the error). Closing
