### ISSUE TITLE
Updates needed for Cran submission

### ISSUE THREAD

**Issue by danagibbon** [dkoslicki/PressPurtCoreAlg#16]
Still outstanding:
* Directory structure (I'd like to put the final url in the vignette)
* Check the `DESCRIPTION` file. Can @marknovak or @dkoslicki  please write a short 'Description' paragraph? Is the author information okay (I put @dkoslicki as the maintainer)? Would you like me to put a link to the github repo? 
* Is "PressPurtCoreAlg" the package name we want to go with?
* Please check the vignettes: [Basic Tutorial](http://htmlpreview.github.io/?https://github.com/dkoslicki/PressPurtCoreAlg/blob/gibbond/vignettes/basic_tutorial.html) and 
[Dependencies tutorial](http://htmlpreview.github.io/?https://github.com/dkoslicki/PressPurtCoreAlg/blob/gibbond/vignettes/dependencies_tutorial.html). It would be nice to have more of a description of what the three main steps done. I copied and pasted from the python docs for the rest of the documentation (that you can access with ?function-name). 
* @danagibbon needs to update to lasted version of R, do final build with that version and submit to cran.
* @marknovak and @dkoslicki feel free to install the latest version and test

Recent updates:
* Fixed prefix option for plotting function
* removed axis legends when plotting all plots
* fixed all cran warnings/notes so submission should go smoothly so now `devtools::build()` results in: 0 errors ✔ | 0 warnings ✔ | 0 notes ✔
* Updated documentation
* Updated vignette so basic tutorial is more detailed
* removed extra tab in  inst/python/ComputeEntryWisePerturbationExpectation.py this should address #14 (My previous fix had a bug in it)
* tested ALL test files. All work that also work in python (unstable error - Martone2017_Model4.csv, wrong format - Wildermuth2017_*.csv, etc.)
* added all of the example data to `inst/extdata/`
* added a short tutorial for how to update the package in the future: `test_r/tutorial-to-update-package.R` (I can add more if you'd like)

We're almost there! To summarize:
1. Update documentation if needed
2. Confirm DESCRIPTION information is up to date
3. rearrange the repo structure and finalize package name
4. Final build and submit to cran

**Comment by dkoslicki** [comment]
R version appears to install without issue using the name `PressPurt`

**Comment by marknovak** [comment]
To summarize what appears to have now been accomplished:
- [x]  Directory structure (I'd like to put the final url in the vignette)   => Done (but see #5)
- [x]  Check the `DESCRIPTION` file. => Looks good
- [x] Can @marknovak or @dkoslicki  please write a short 'Description' paragraph?  => Apparently done
- [x] Is the author information okay (I put @dkoslicki as the maintainer)?   => Yes
- [ ] Would you like me to put a link to the github repo? 
- [x] Is "PressPurtCoreAlg" the package name we want to go with?   => Updated to "PressPurt"
- [x] Please check the vignettes: [Basic Tutorial](http://htmlpreview.github.io/?https://github.com/dkoslicki/PressPurtCoreAlg/blob/gibbond/vignettes/basic_tutorial.html) and 
[Dependencies tutorial](http://htmlpreview.github.io/?https://github.com/dkoslicki/PressPurtCoreAlg/blob/gibbond/vignettes/dependencies_tutorial.html). It would be nice to have more of a description of what the three main steps done. I copied and pasted from the python docs for the rest of the documentation (that you can access with ?function-name).  => Links no longer valid, contents moved to README.md's and links therein.

**Comment by dkoslicki** [comment]
Last remaining issue is #26 . Closing this one
