### ISSUE TITLE
Error in PreprocessMatrix

### ISSUE THREAD

**Issue by rockowd** [dkoslicki/PressPurtCoreAlg#19]
``> PreProsMatrix <- PreprocessMatrix(input_file = infile, output_folder = NULL, max_bound = 10, threads = 2)``
Error in `[.python.builtin.object`(tt$asymptotic_stability, , , 1) : 
  unused arguments (alist(, 1))

**Comment by marknovak** [comment]
Solved by forcing a re-install of our package after install of Anaconda
