### ISSUE TITLE
Typo in repository name

### ISSUE THREAD

**Issue by dkoslicki** [dkoslicki/PressPurtCoreAlg#21]
@marknovak Amazingly, the following has escaped our attention until just now: it's spelled "perturbation", not "purturbation", hence the name of the algorithm should be "PressPert", not "PressPurt"

**Comment by dkoslicki** [comment]
Opted to stick with the old name of "PressPurt" (creative license?). Renamed repo to remove "CoreAlg"

**Comment by marknovak** [comment]
Works for me!
