### ISSUE TITLE
Consider computing average number of mispredictions more carefully

### ISSUE THREAD

**Issue by dkoslicki** [dkoslicki/PressPurtCoreAlg#25]
For example, instead of dividing by `n^2` [here](https://github.com/dkoslicki/PressPurt/blob/master/Python_version/scripts/GenerateEntryWiseFigures.py#L277) and [here](https://github.com/dkoslicki/PressPurt/blob/master/Python_version/src/NumSwitch.py#L225), only divide by the number of non-zero entries in the jacobian (as you *can't* get the zero entries incorrect).

**Comment by marknovak** [comment]
We did consider this when we figured it all out for the first paper, didn't we?  The net effects matrix has no zero entries.

**Comment by dkoslicki** [comment]
Oh, of course! I mixed up the Jacobian and the net effects matrix. I'll close this (non)issue.
