### ISSUE TITLE
CRAN Submission

### ISSUE THREAD

**Issue by dkoslicki** [dkoslicki/PressPurtCoreAlg#26]
It's my understanding that CRAN re-runs the vignettes when you submit the package. They will not pass CRAN's test environment because it doesn't have python, etc. 
I briefly looked for a solution and I ran into static vignettes. All of the posts are from 7+ years ago so I don't know if that solution will work, but I can look into it if you'd like.

_Originally posted by @danagibbon in https://github.com/dkoslicki/PressPurt/issues/17#issuecomment-539242760_

**Comment by dkoslicki** [comment]
Hmm...  I didn't think about Python causing a problem for CRAN.
But yes, @danagibbon, please do look to see if static vignettes will work.

_Originally posted by @marknovak in https://github.com/dkoslicki/PressPurt/issues/17#issuecomment-539726072_

**Comment by marknovak** [comment]
https://CRAN.R-project.org/package=PressPurt
