### ISSUE TITLE
Clean-up R version README

### ISSUE THREAD

**Issue by marknovak** [dkoslicki/PressPurtCoreAlg#29]
I think we need to cleanup to README, removing repeated information and providing cleaner examples of returned information esp. with regard to virtual environments.  Currently, for example, the README refers to multiple existing environments (Test, PressPurt, test-r, reticulate-r), whereas most users will have none to start with.

**Comment by marknovak** [comment]
It seems to me that few if any users will need multiple environments.  Hence, since we show them how to create them we might as well show (or link to) instruction for how to remove them: (e.g., [LINK](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#removing-an-environment))

**Comment by dkoslicki** [comment]
Good point! Feel free to add that to the readme after the installation instructions (perhaps just before the virtualenv instructions).

**Comment by marknovak** [comment]
I believe this is now all accomplished.
