### ISSUE TITLE
ComputeEntryWisePertubation function producing following error

### ISSUE THREAD

**Issue by rockowd** [dkoslicki/PressPurtCoreAlg#32]
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: 'float' object cannot be interpreted as an integer

Detailed traceback: 
  File "<__array_function__ internals>", line 6, in linspace
  File "/Users/davidrockow/anaconda3/envs/r-reticulate/lib/python3.7/site-packages/numpy/core/function_base.py", line 113, in linspace
    num = operator.index(num)

I am open to suggestions, thanks

**Comment by rockowd** [comment]
Fixed it

**Comment by marknovak** [comment]
> Fixed it

Apparently as simple as not running the following!?!
```
find_python()
set_python("r-reticulate", verbose = TRUE)
py_depend("r-reticulate")
```
