### ISSUE TITLE
Some invalid example matrices

### ISSUE THREAD

**Issue by dkoslicki** [dkoslicki/PressPurtCoreAlg#5]
There are a few example matrices that appear to be invalid:
Qualitative/Hansen2017 singular
~~Qualitative/Wildermuth2017_ComplexReduced not a square matrix~~
~~Qualitative/Wildermuth2017_SimpleDetailed not a square matrix~~
Qualitative/Dambacher2003_j not stable
Qualitative/Martone2017_Model3 not stable
Qualitative/Dambacher2003_o singular
Qualitative/Martone2017_Model1 not stable
~~Qualitative/Wildermuth2017_ComplexDetailed not a square matrix~~
Qualitative/Martone2017_Model2 not stable
~~Qualitative/Wildermuth2017_SimpleReduced not a square matrix~~

Quantitative/Schmitz1997 not stable
Quantitative/Schmitz1997_error not stable

**Comment by dkoslicki** [comment]
@marknovak Note that for the Wildermuth examples, they have been uploaded as tsv files, not csv files. I've added the ability to read tsv files as well.

**Comment by marknovak** [comment]
Dambacher2003_j and Dambacher2003_o each had a misplaced link, so please try again.

In the process, I found errors in...
Dambacher2003_b
Dambacher2003_c
Dambacher2003_e
Dambacher2003_h
Dambacher2003_i
Dambacher2003_l
Dambacher2003_r
...due to a systematic mistake I made in the way I tried to simplify/speed up matrix construction, so please try them again too.

Still need to check the other ones...

**Comment by marknovak** [comment]
Hansen2017 is correct (as given in their Fig. 1) and is indeed (and obviously so) singular (the links for nodes 5 and 6 are identical).  Will send the authors an email to see what's up.

**Comment by dkoslicki** [comment]
All the Dambacher matrices you found errors in now work, with the exception of Dambacher2003_o, which is still singular.

**Comment by dkoslicki** [comment]
For completeness' sake, here are the current problem matrices:
Dambacher2003_o.csv    singular
Hansen2017.csv    singular
Wildermuth2017_ComplexDetailed.csv    not stable
Wildermuth2017_ComplexReduced.csv    not stable
Martone2017_Model3.csv    not stable
Martone2017_Model1.csv    not stable
Martone2017_Model2.csv    not stable
Schmitz1997.csv    not stable

**Comment by marknovak** [comment]
Removed Node 6 of Hansen2017 (identical to Node 7, making it singular).

**Comment by marknovak** [comment]
Dambacher2003_o.csv is definitely as given in paper.  Nodes 2 & 3 are identical.  ("Based on Schmitz1997.)

**Comment by marknovak** [comment]
Removed Nitrogen from Schmitz1997.

**Comment by dkoslicki** [comment]
Hansen2017 works with no error now.

Unfortunately, removing Nitrogen from Schmitz1997 didn't fix the stability (one eigenvalue is 0.02918).

**Comment by dkoslicki** [comment]
@marknovak Here are the current matrices are are causing issues:
./Qualitative/Martone2017_Model3.csv -> not stable
./Qualitative/Martone2017_Model2.csv -> not stable
./Qualitative/Martone2017_Model1.csv -> not stable
./Qualitative/Dambacher2003_o.csv -> singular matrix
./Quantitative/Schmitz1997.csv -> not stable
./Quantitative/Schmitz1997_error.csv -> not stable

Let me know if you have any problem with me just deleting these.

**Comment by marknovak** [comment]
I suggest we

-  remove all "ExampleJacobians" with the exception of those contained within the "Modules" folder (I have copies for use in a subsequent paper)
- move the "ExampleJacobians" folder to a different location (outside "Python_version")
- include the Ecoli jacobian that we plan to use in the Application Note, and include its analysis as performed in the Note in the vignette.

**Comment by marknovak** [comment]
Note that moving the "ExampleJacobians" folder will also require updates to the help docs.

**Comment by marknovak** [comment]
As an alternative to moving the folder of "ExampleJacobians" to a different location, we could instead include them in the R-package as built-in data.  [http://r-pkgs.had.co.nz/data.html](http://r-pkgs.had.co.nz/data.html)

**Comment by dkoslicki** [comment]
My understanding is Dana has already included the Jacobians in the R package. In the link you gave, it says to place raw data in `inst/extdata` and indeed, Dana put the `ExampleJacobians` in that folder. I think this is why the data can be accessed as in the vignette:
```R
infile <- system.file("extdata", "Modules", "IGP.csv", package = "PressPurt")
```
Personally, I would be fine with moving the non-Module Jacobians outside, but would prefer to keep them on Github (things tend to get misplaced otherwise).

+1 to including the e coli example. @marknovak would you want to update the vignette (given you're more familiar with R)?

**Comment by dkoslicki** [comment]
All non-module example Jacobians removed. Browse the repo at [this commit](https://github.com/dkoslicki/PressPurt/tree/43d2756cdf3dc9586e7c8c1ac2066def8326a49e) if you want to see what they were. Closing
